version: '3.2'

services:
  mysql:
    container_name: nova-core-mysql
    image: bitnami/mariadb:latest
    ports:
      - "3307:3306"
    environment:
      - MARIADB_DATABASE=novaecommerce
      - MARIADB_ROOT_USER=root
      - MARIADB_ROOT_PASSWORD=admin

